```c
int i,j;
double x = 0.0;
#pragma omp parallel for
for (i = 0; i < DIMENSION; i++)
for (j = 0; j < DIMENSION; j++)
  if (i >= j)
     *(*Matrix + i * DIMENSION + j) = x++;
  else
     *(*Matrix + i * DIMENSION + j) = 1.0;
```

In [8]:
from pandas import DataFrame


def matrix(dimension: int):
    _matrix = []
    x = 0
    for i in range(dimension):
        # add a row to the matrix
        _matrix.append([])
        for j in range(dimension):
            if i >= j:
                _matrix[-1].append(x)
                x += 1
            else:
                _matrix[-1].append(1)
    return DataFrame(_matrix)

In [10]:
matrix(14)

    0   1   2   3   4   5   6   7   8    9    10   11   12   13
0    0   1   1   1   1   1   1   1   1    1    1    1    1    1
1    1   2   1   1   1   1   1   1   1    1    1    1    1    1
2    3   4   5   1   1   1   1   1   1    1    1    1    1    1
3    6   7   8   9   1   1   1   1   1    1    1    1    1    1
4   10  11  12  13  14   1   1   1   1    1    1    1    1    1
5   15  16  17  18  19  20   1   1   1    1    1    1    1    1
6   21  22  23  24  25  26  27   1   1    1    1    1    1    1
7   28  29  30  31  32  33  34  35   1    1    1    1    1    1
8   36  37  38  39  40  41  42  43  44    1    1    1    1    1
9   45  46  47  48  49  50  51  52  53   54    1    1    1    1
10  55  56  57  58  59  60  61  62  63   64   65    1    1    1
11  66  67  68  69  70  71  72  73  74   75   76   77    1    1
12  78  79  80  81  82  83  84  85  86   87   88   89   90    1
13  91  92  93  94  95  96  97  98  99  100  101  102  103  104

In [9]:
matrix(14).T

    0   1   2   3   4   5   6   7   8   9   10  11  12   13
0    0   1   3   6  10  15  21  28  36  45  55  66  78   91
1    1   2   4   7  11  16  22  29  37  46  56  67  79   92
2    1   1   5   8  12  17  23  30  38  47  57  68  80   93
3    1   1   1   9  13  18  24  31  39  48  58  69  81   94
4    1   1   1   1  14  19  25  32  40  49  59  70  82   95
5    1   1   1   1   1  20  26  33  41  50  60  71  83   96
6    1   1   1   1   1   1  27  34  42  51  61  72  84   97
7    1   1   1   1   1   1   1  35  43  52  62  73  85   98
8    1   1   1   1   1   1   1   1  44  53  63  74  86   99
9    1   1   1   1   1   1   1   1   1  54  64  75  87  100
10   1   1   1   1   1   1   1   1   1   1  65  76  88  101
11   1   1   1   1   1   1   1   1   1   1   1  77  89  102
12   1   1   1   1   1   1   1   1   1   1   1   1  90  103
13   1   1   1   1   1   1   1   1   1   1   1   1   1  104